# -*- coding: utf-8 -*-
"""CSST102 Housing and Iris - AGOJO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/186qKU5cSxYhcI5GcvEmqbALGsgVseGak

# **Setup**
"""

import sklearn
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pandas as pd

"""# **Loading Dataset**"""

iris = load_iris(as_frame=True)
df = iris.frame

"""# **Dataset Exploration**"""

print(df.describe())
print("Target classes;", iris.target_names)

print(df['target'].value_counts())

"""# **Train Test Split & Baseline Model**"""

X = df[iris.feature_names]
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=200)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

"""# **Data Evaluation**"""

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""## Load Dataset

"""

df = pd.read_csv("/content/housing.csv")
df.head()

"""## Explore Dataset

"""

display(df.head())
display(df.info())
display(df.describe())

"""## Train Test Split

"""

X = df.drop(['median_house_value', 'ocean_proximity'], axis=1)
y = df['ocean_proximity']

combined_df = pd.concat([X, y], axis=1).dropna()
X = combined_df.drop('ocean_proximity', axis=1)
y = combined_df['ocean_proximity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

display(X_train.head())
display(y_train.head())

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)