# -*- coding: utf-8 -*-
"""csst102_mp2_agojo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15nKCOPts90xrFgD1a7k5TDJK1a7yj7Te

Imports
"""

import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, learning_curve
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

"""Load Dataset"""

df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df.head()

"""Preparing Dataset"""



"""Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print('Train: ', X_train.shape, ' Test: ', X_test.shape)

"""Logistic Regression"""

model = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=2000, solver='liblinear'))
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

"""Cross-Validation (5- fold)"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42) if len(np.unique(y_train)) > 1 else 5
cv_scores = cross_val_score(model, X_train, y_train, cv=cv, scoring='accuracy')

print("CV mean acc: %.4f ± %.4f" % (cv_scores.mean(), cv_scores.std()))

"""Confusion Matrix"""

print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))

"""Learning Curve"""

train_sizes, train_scores, test_scores = learning_curve(model, X_train, y_train, cv=cv,
                                                            train_sizes=[0.1,0.3,0.5,0.7,1.0], n_jobs=-1)
plt.figure(figsize=(6,4))
plt.plot(train_sizes, train_scores.mean(axis=1), marker='o', label='Train')
plt.plot(train_sizes, test_scores.mean(axis=1), marker='s', label='CV')
plt.xlabel('Training set size')
plt.ylabel('Accuracy')
plt.title('Learning Curve (LogisticRegression)')
plt.legend()
plt.grid(True)
plt.show()

"""# Short Report:

The logistic regression model of the Sleep Health and Lifestyle Dataset has achieved a 97% accuracy with consistent performance in cross-validation which indicates good generalization. The confusion matrix is shown to confuse minority classes such as Insomnia and Sleep Apnea due to the overlapping patterns and limited samples despite correctly clarifying most cases. The learning curve then suggests that the model would benefit from more stabilized data to show low bias making a better fit. An improvement that can be done on the model is to use class balancing techniques to explore flexible algorithms and collect more data.
"""